# Generated by Django 5.1 on 2024-08-18 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cursos',
            new_name='Curso',
        ),
        migrations.RenameModel(
            old_name='Estudantes',
            new_name='Estudante',
        ),
    ]
